### ISSUE TITLE
Command Line changes in 2023.6

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#102]
June release has brought change to how `command_line` integration is configured in YAML files.
This required change to how code looks and how files are set
Due to my split configuration, I've added folder `command_line `and subfolders for `switch`, `sensor `and `binary_sensor`, as only those are currently used in my setup.

Code is easy to change.
Old: 
```
platform: command_line
command: /bin/bash -c "(echo > /dev/tcp/192.168.1.35/1883) > /dev/null 2>&1 && echo open || echo closed"
name: MQTT status
payload_off: "closed"
payload_on: "open"
scan_interval: 300
device_class: 'problem'
```

Is now:
```
binary_sensor:
#  platform: command_line
  name: MQTT status
  unique_id: 44b85908-2738-4b54-8ded-fb6314c06c5b
  command: /bin/bash -c "(echo > /dev/tcp/192.168.1.35/1883) > /dev/null 2>&1 && echo open || echo closed"
  payload_off: "closed"
  payload_on: "open"
  scan_interval: 300
  device_class: 'problem'
```

And it all is called within integrations folder like this:

`command_line: !include_dir_merge_list ../entities/command_line`

Note that it has to use `inclide_dir_merged_list`.
