### ISSUE TITLE
Bubble Card Examples

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#109]
Here are few examples from my configuration. You need to adjust entities to match your config:

Living room bubble card:
![image](https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/795ef992-5c1d-4b67-9202-c2f4db4275af)

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#living-room'
    name: Living room
    icon: phu:living-room
    entity: light.living_room_light
    state: sensor.living_room_temperature
    state_unit: °C
    width_desktop: 600px
    margin_top_mobile: 18px
    margin_top_desktop: 74px
    auto_close: 15000
    trigger_entity: binary_sensor.living_room_motion_occupancy
  - type: custom:mushroom-climate-card
    entity: climate.living_room
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: mdi:ceiling-light-multiple-outline
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.entrance
        show_state: true
        icon: mdi:desk-lamp
      - type: custom:bubble-card
        card_type: button
        entity: light.standing
        show_state: true
        button_type: slider
        icon: mdi:floor-lamp-torchiere
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: light.tv
        show_state: true
        button_type: slider
        icon: mdi:desk-lamp
      - type: custom:bubble-card
        card_type: button
        entity: light.corner
        show_state: true
        button_type: slider
        icon: mdi:desk-lamp
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.ceilling
    show_state: true
    icon: mdi:spotlight-beam
  - type: custom:bubble-card
    card_type: separator
    name: Appliances
  - type: custom:bubble-card
    card_type: button
    entity: vacuum.roborock_s5_max
    icon: mdi:robot-vacuum
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-media-player-card
        entity: media_player.lg_webos_tv_lf652v
      - type: custom:mushroom-media-player-card
        entity: media_player.google_tv
  - type: custom:mushroom-media-player-card
    entity: media_player.sonos_roam_sl_2

```

Dining room bubble card:

![image](https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/143c5dd5-311f-46f5-b5c6-1cd0d2e63667)

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#dining-room'
    name: Dining room
    icon: phu:rooms-dining
    entity: light.dining_room_light
    state: sensor.dining_room_temperature
    state_unit: °C
    width_desktop: 600px
    margin_top_mobile: 18px
    margin_top_desktop: 74px
    auto_close: 15000
  - type: custom:mushroom-climate-card
    entity: climate.dining_room
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: mdi:ceiling-light-multiple-outline
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: switch
        entity: light.left
        show_state: true
        icon: mdi:ceiling-light
      - type: custom:bubble-card
        card_type: button
        entity: light.right
        show_state: true
        button_type: switch
        icon: mdi:ceiling-light
  - type: custom:bubble-card
    card_type: button
    entity: light.rice_lights
    show_state: true
    button_type: slider
    icon: mdi:string-lights
  - type: custom:bubble-card
    card_type: separator
    name: Appliances
  - type: custom:bubble-card
    card_type: button
    entity: media_player.display_me
    icon: phu:nest-hub

```

Kitchen bubble card:

![image](https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/e52c2539-1c0a-4afe-bdd3-8a1ed6fa643c)

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#kitchen'
    name: Kitchen
    icon: mdi:fridge
    entity: light.kitchen
    state: sensor.kitchen_temperature
    state_unit: °C
    width_desktop: 600px
    margin_top_mobile: 18px
    margin_top_desktop: 74px
    auto_close: 15000
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: mdi:ceiling-light-multiple-outline
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: switch
        entity: light.kitchen_countertop
        show_state: true
        icon: mdi:floor-lamp-outline
      - type: custom:bubble-card
        card_type: button
        entity: light.oven
        show_state: true
        button_type: slider
        icon: mdi:ceiling-light
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: light.sink
        show_state: true
        button_type: slider
        icon: mdi:ceiling-light
      - type: custom:bubble-card
        card_type: button
        entity: light.fridge
        show_state: true
        button_type: slider
        icon: mdi:ceiling-light
  - type: custom:bubble-card
    card_type: separator
    name: Appliances
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: switch.shelly_shplg_s_b4944b
        icon: mdi:dishwasher
      - type: custom:bubble-card
        card_type: button
        entity: switch.shelly_shplg_s_01e22b
        icon: mdi:washing-machine

```

**Comment by BeardedTinker** [comment]
Zita Room bubble card:

![image](https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/b9cac2ca-7c64-415c-92d3-4fef45aa637b)


```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#zita-room'
    name: Zita room
    icon: mdi:alpha-z
    entity: light.zita_room_lights
    state: sensor.zita_room_temperature
    state_unit: °C
    width_desktop: 600px
    margin_top_mobile: 18px
    margin_top_desktop: 74px
    auto_close: 15000
    trigger_entity: binary_sensor.contact_motion_detected
  - type: custom:mushroom-climate-card
    entity: climate.zita_room
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: mdi:ceiling-light-multiple-outline
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        button_type: slider
        entity: light.zita_desk_lights_2
        show_state: true
        icon: mdi:desk-lamp
      - type: custom:bubble-card
        card_type: button
        entity: light.zita_tabletop
        show_state: true
        button_type: slider
        icon: phu:light-string
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: light.zita_ceiling
        show_state: true
        button_type: slider
        icon: mdi:ceiling-light
      - type: custom:bubble-card
        card_type: button
        entity: light.zita_desk_light
        show_state: true
        button_type: slider
        icon: mdi:string-lights
  - type: custom:bubble-card
    card_type: separator
    name: Appliances
  - group: true
    hide:
      controls: true
    icon: phu:home-mini
    icon_state: true
    tts:
      language: hr-hr
      platform: microsoft
    type: custom:mini-media-player
    entity: media_player.mini_me

```
