### ISSUE TITLE
Linptech ES1 presence sensor automation example

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#110]
Here is the sample automation created for Limptech presence sensor:

```
alias: Linptech for Stream Desk
description: ""
trigger:
  - type: motion
    platform: device
    device_id: f46a7d284f919918254c6021e040b0da
    entity_id: eba83449aa09a124c6f4a16182e7e01d
    domain: binary_sensor
    id: occupied
  - type: no_motion
    platform: device
    device_id: f46a7d284f919918254c6021e040b0da
    entity_id: eba83449aa09a124c6f4a16182e7e01d
    domain: binary_sensor
    id: unoccupied
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - occupied
        sequence:
          - type: turn_on
            device_id: cf8eb69698570241e3703193bd4f957a
            entity_id: b58d29a1fb6e0198c275daa2820e74a8
            domain: light
      - conditions:
          - condition: trigger
            id:
              - unoccupied
        sequence:
          - type: turn_off
            device_id: cf8eb69698570241e3703193bd4f957a
            entity_id: b58d29a1fb6e0198c275daa2820e74a8
            domain: light
mode: single

```
