### ISSUE TITLE
GTFS examples

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#113]
As I didn't cover everything in video, here are few other things I'm using.

For example, for individual tracking, I've created for each family member it's "in vicinity" sensor:
<img width="401" alt="image" src="https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/a4bb881b-0d91-4df7-b017-f01b62ec7073">

It will than create a bunch (if exist) stops for all transport types.

These can be used as map overlays:

<img width="823" alt="image" src="https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/00721d1e-243d-4fde-b22b-50b49e87f7de">
Code for card looks as follows:
```
type: custom:auto-entities
card:
  type: map
  hours_to_show: 2
  dark_mode: true
  default_zoom: 17
  auto_fit: true
filter:
  include:
    - entity_id: '*_local_stop_person_andrej*'
    - entity_id: person.andrej
show_empty: true
```
Also, you can create flex table with data for everyone or just on person:

<img width="318" alt="image" src="https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/d8bd0a97-d58d-418b-a8eb-0ff193b53edf">

```
type: custom:auto-entities
filter:
  include:
    - name: '*local_stop*'
  exclude:
    - state: unavailable
card:
  type: custom:flex-table-card
  clickable: true
  max_rows: 30
  title:  ZET departures
  sort_by:
    - next_departures_lines
  columns:
    - hidden: true
      data: next_departures_lines
      modify: x.departure
    - name: Route
      data: next_departures_lines
      modify: '''<ha-icon icon='' + x.icon + ''></ha-icon>'' + x.route'
    - name: Time
      data: next_departures_lines
      modify: x.departure
    - name: Stop
      data: next_departures_lines
      modify: x.stop_name
    - name: Headsign
      data: next_departures_lines
      modify: x.headsign
  css:
    table+: 'padding: 0px'
  card_mod:
    style: |
      ha-card {
        overflow: auto;
        max-height: 500px;
      }
```
