### ISSUE TITLE
OpenEPaper Link code examples.

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#114]
This is code from the video.

![image](https://github.com/BeardedTinker/Home-Assistant_Config/assets/47822612/0133cea2-7873-4de1-8f7a-b5cdbed5b2db)

```
service: open_epaper_link.drawcustom
data:
  background: white
  ttl: 300
  payload:
    - type: rectangle
      outline: red
      fill: white
      width: 1
      x_start: 5
      y_start: 5
      x_end: 289
      y_end: 118
    - type: icon
      value: heart-pulse
      x: 10
      "y": 10
      size: 16
      color: red      
    - type: text
      value: Heart rate {{states('sensor.heart_rate')}}
      font: ppb.ttf
      x: 30
      "y": 10
      size: 16
      color: black
    - type: icon
      value: heart
      x: 10
      "y": 28
      size: 16
      color: red
    - type: text
      value: Resting heart rate {{states('sensor.resting_heart_rate')}}
      font: ppb.ttf
      x: 30
      "y": 28
      size: 16
      color: black      
    - type: icon
      value: water-percent
      x: 10
      "y": 46
      size: 16
      color: red        
    - type: text
      value: Oxygen saturation {{states('sensor.oxygen_saturation')}}
      font: ppb.ttf
      x: 30
      "y": 46
      size: 16
      color: black           
    - type: line
      fill: black
      width: 1
      x_start: 10
      y_start: 66
      x_end: 283
      y_end: 66   
    - type: icon
      value: walk
      x: 10
      "y": 70
      size: 16
      color: red        
    - type: text
      value: Steps daily {{states('sensor.steps_daily')}}
      font: ppb.ttf
      x: 30
      "y": 70
      size: 16
      color: black         
    - type: icon
      value: cup-water
      x: 10
      "y": 88
      size: 16
      color: red        
    - type: text
      value: Hydration {{states('sensor.hydration')}} l
      font: ppb.ttf
      x: 30
      "y": 88
      size: 16
      color: black         
target:
  entity_id: open_epaper_link.0000021C63473B10
```
