### ISSUE TITLE
Automation YAML code for Glovo notification video

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#115]
Here is the code that was used in video:

```
- id: '1718643534387'
  alias: Notification from Glovo App - Andrej
  description: Get notifications from Glovo and redistribute
  trigger:
  - platform: state
    entity_id:
    - sensor.pixel_7_pro_last_notification
    attribute: post_time
  condition:
  - condition: state
    entity_id: sensor.pixel_7_pro_last_notification
    attribute: package
    state: com.glovo
  action:
  - service: persistent_notification.create
    data:
      message: Glovo message {{state_attr(last_notification, 'android.title')}}. {{states(last_notification)}}
  variables:
    last_notification: sensor.pixel_7_pro_last_notification
  mode: single
```
You need to substitute `sensor.pixel_7_pro_last_notification` with whatever name of your last_notification sensor is.
Also, in condition, substitute state with name of the app you want to get notifications from instead of `com.glovo` that is use here.
