### ISSUE TITLE
Automate GitHub tasks a bit more

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#12]
Idea is to automate tasks with GitHub:
- open issues when needed
- create and/or reopen issues for HA updates with Travis testing 
- same for HACS updates
This will be based on:
https://github.com/jcallaghan/home-assistant-config/issues/103
https://github.com/kylegordon/home-assistant-config/blob/master/packages/update_notifier.yaml

**Comment by BeardedTinker** [comment]
I know that there is probably EXCELLENT and obvious reason, but I can't figure this error out...

```
Log Details (WARNING)
Logger: homeassistant.components.rest_command
Source: components/rest_command/__init__.py:130
Integration: RESTful Command (documentation, issues)
First occurred: 10:19:59 PM (4 occurrences)
Last logged: 10:55:25 PM

Error. Url: https://api.github.com/repos/BeardedTinker/Home-Assistant_Config/issues/14/comments. Status code 422
```

Any suggestion on this would be great...

**Comment by BeardedTinker** [comment]
Hmm - can't figure this one out for the life of me.
When working with state of an issue - I can open/close it with automation:

```
new_version_github_issue:
  url: "https://api.github.com/repos/BeardedTinker/Home-Assistant_Config/issues/14"
  method: PATCH
  headers:
    Authorization: !secret github_token2
  payload: '{"state":"{{ status }}"}'
```
And this works...

BUT when I try to post to body with:

```
new_version_github_issue_comment:
  url: 'https://api.github.com/repos/BeardedTinker/Home-Assistant_Config/issues/14/comments'
  method: POST
  headers:
    Authorization: !secret github_token2
    payload: '{"body":" {{ message }}"}' 
```

I get error that is listed above - Error code 422
Anyone has any idea? @pinkywafer - I've used your code - maybe you had issue like that? Is that maybe related to scope of the private token (I'm using for this token only repo:).

https://github.com/pinkywafer/Home-Assistant_Config/issues/4
