### ISSUE TITLE
Solar power preparation

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#2]
This change will be regarding tracking of apartment energy usage between two cycles: day and night.
In theory, when there is enough data available, it could make it easy to calculate your energy usage and create optimal off-grid/inline PV system + battery capacity needed.

**Comment by BeardedTinker** [comment]
First part is done #3fbba6988880b873820270a1e76287cb90ab29cb

**Comment by CCOSTAN** [comment]
Would love to see a video explaining this in more detail.

**Comment by BeardedTinker** [comment]
> Would love to see a video explaining this in more detail.

Hopefully it will be worth doing it, but that was the general idea.

**Comment by BeardedTinker** [comment]
So far, so good - it's working nicely...
This is output from .csv file that's created at midnight  
```
Home Assistant notifications (Log started: 2020-08-11T23:50:50.855669+00:00)
--------------------------------------------------------------------------------
2020-08-11,0.15,1.11,7.63,None,None,unknown,6.81
2020-08-12,6.06,3.12,9.18,None,None,unknown,7.82
2020-08-13,7.75,3.18,10.93,None,None,unknown,9.52
2020-08-14,8.32,4.10,12.42,None,None,unknown,10.66
2020-08-15,9.56,3.01,12.57,None,None,unknown,10.98
```
And there is screenshot from GUI
![image](https://user-images.githubusercontent.com/47822612/90328946-e94b2980-dfa0-11ea-8289-ff3070b31b40.png)

One is tracking peak/offpeak electricity, and other one is tracking electricity usage during da and night.

**Comment by BeardedTinker** [comment]
And nice visual representation of energy usage vs day/night:
![image](https://user-images.githubusercontent.com/47822612/90329024-77bfab00-dfa1-11ea-9c6f-acfcf7635de0.png)

Have to stress once again this all was inspired and based on following project:
https://community.home-assistant.io/t/daily-energy-monitoring/143436

**Comment by BeardedTinker** [comment]
This has been working very nicely for last 30+ days.
Still have to add expand on this, but closing for now.

**Comment by BeardedTinker** [comment]
This is my Lovelace card (HACS mini graph card).
It uses binary sensor created above and current consumption from Shelly EM.
```
color_thresholds:
  - color: '#039BE5'
    value: 0
  - color: '#0da035'
    value: 600
  - color: '#e0b400'
    value: 1200
  - color: '#e45e65'
    value: 2400
color_thresholds_transition: hard
entities:
  - sensor.shelly_em_current_consumption
  - color: 'rgba(0,0,255,1)'
    entity: binary_sensor.dark_outside
    show_line: false
    y_axis: secondary
group: false
hour24: true
hours_to_show: 24
line_width: 4
points_per_hour: 4
show:
  extrema: true
  fill: fade
  icon: true
  labels: false
  name: true
  state: true
state_map:
  - label: Day
    value: 'off'
  - label: Night
    value: 'on'
style: |
  ha-card {
    border: solid 2px var(--primary-color);
  }
type: 'custom:mini-graph-card'

```
