### ISSUE TITLE
Chromecast Radio streaming

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#29]
I've had for 2 years now few input fields and scripts, from the time I was trying to get this working.
Now it's time to get it all working:
e0ea41e54889aa1bf2e2327dc47f5158d39da7c1 - this one made it work
f80c4c63ffbe272e75c7338ccdf25283f76f6a79 - in this I've added more improvements

Following is used in more complexed version in Lovelace to show logo and add some better controls.

```
cards:
  - entities:
      - entity: input_select.radio_station
      - entity: input_text.custom_radio
      - entity: input_select.chromecast_radio
      - entity: switch.radio_volume_down
      - entity: switch.radio_mute
      - entity: switch.radio_volume_up
      - entity: switch.radio_stop
      - entity: switch.radio_play
    entity: input_select.radio_station
    state_image:
      Antena Zagreb: /local/radio/antena-zagreb.jpg
      Narodni: /local/radio/narodni-radio.jpg
      HKR: /local/radio/otvoreni.jpg
      HRT1: /local/radio/otvoreni.jpg
      HRT2: /local/radio/otvoreni.jpg
      Otvoreni: /local/radio/otvoreni.jpg
      Radio Marija: /local/radio/otvoreni.jpg
      Radio Postaja Mir Međugorje: /local/radio/otvoreni.jpg
      yammat FM: /local/radio/yammat-fm.jpg
      Stopped: /local/radio/otvoreni.jpg
    type: picture-glance
  - entities:
      - entity: sensor.radio_station_selected
      - entity: sensor.speaker_selected
      - entity: input_number.volume_radio
    show_header_toggle: false
    type: entities
type: vertical-stack
```
 Still to do is fix naming convention - want to get everything easily searchable - all needs to start with radio_*
