### ISSUE TITLE
Zigbee2MQTT switches, timers etc

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#38]
Upon the request from James Sheeran on YouTube to record video about enabling Join in Zigbee2MQTT from within Home Assistant, here are few new additions:
- Input Number filed - to select how long do you want to allow new devices to join (in minutes)
- Timer - to enable HA native timer, based on input above
- Enable/Disable automations to of course enable or disable joining (enabled via switch, disabled via timer)
- Interview done automation, to receive notification when new device has been added
- Switch to start/enable join

Still not tested, but this should work. And I really wished I added this sooner.

This is of course, based on official documentation - https://www.zigbee2mqtt.io/integration/home_assistant.html
With minor modifications.

**Comment by BeardedTinker** [comment]
Following can be used in UI for card:

```
title: Zigbee2MQTT
type: entities
show_header_toggle: false
entities:
  - entity: sensor.zigbee2mqtt_bridge_state
  - type: divider
  - entity: input_number.zigbee2mqtt_join_minutes
  - entity: timer.zigbee_permit_join
```
And it will create this visual interface:
![image](https://user-images.githubusercontent.com/47822612/103379397-c3ed3100-4ae5-11eb-8ecd-6175e2731271.png)
