### ISSUE TITLE
SwitchBot Humidifier and Meter

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#77]
Thanks to SwitchBot for sending me Humidifier, Meter (and one additional device that is NOT Curtain).

The challenge is to add SwitchBot Humidifier and Meter in Home Assistant - without using ESP board as Bluetooth gateway.
And for that I've used [SwitchBot API](https://github.com/OpenWonderLabs/SwitchBotAPI) that allows you to communicate with devices via GET/POST.

[Official documentation ](https://github.com/OpenWonderLabs/SwitchBotAPI#getting-started)will help you on following steps.
First you need to install the app as per manual and add devices into SwitchBot app.
Next step is to enable developers menu and retrieve API key from mobile app.

From any command line (you can use HA terminal for this) type following command:
`curl -H "Authorization: API_KEY" https://api.switch-bot.com/v1.0/devices`
This will list ALL devices that are attached to SwitchBot App.

Find DeviceID that matches device you want to add - for ex:
`{"statusCode":100,"body":{"deviceList":[{"deviceId":"AAAAAAAA","deviceName":"Humidifier ","deviceType":"Humidifier","enableCloudService":true,"hubDeviceId":"000000000000"},{"deviceId":"BBBBBBBB","deviceName":"Temp","deviceType":"Meter","enableCloudService":false,"hubDeviceId":"000000000000"},"message":"success"}`
Here you can see 2 devices - deviceID: AAAAAAAA for Humidifier and deviceID: BBBBBBBB for Meter.

For Home Assistant we will need API KEY and device id for both Humidifier and Meter if you have it - if you don't have it, just skip.

We can start with switch in Home Assistant to enable power on/off function for Humidifier.

in `switch` section of `configuration.yaml` (or in `switch.yaml`) add following:
```
platform: command_line
switches: 
  switchbot_humidifier:
    command_on: "/usr/bin/curl -X POST -H 'Content-Type: application/json' -H 'Authorization: API_KEY' -d '{\"command\": \"turnOn\"}' https://api.switch-bot.com/v1.0/devices/DEVICE_ID/commands"
    command_off: "/usr/bin/curl -X POST -H 'Content-Type: application/json' -H 'Authorization: API_KEY' -d '{\"command\": \"turnOff\"}' https://api.switch-bot.com/v1.0/devices/DEVICE_ID/commands"
    friendly_name: Switchbot Humidifier
```
Just substitute with your API_KEY and DEVICE_ID of your Humidifier.
(If you want to use secrets file, just copy whole command to secrets file).

NOTE: In order for code below to work, you have to add to `secrets.yaml` file following variables:

```
sbot_api: YOUR_SWITCHBOT_API_KEY
sbot_hum_on: "/usr/bin/curl -X POST -H 'Content-Type: application/json' -H 'Authorization: API_TOKEN ' -d '{\"command\": \"turnOn\"}' https://api.switch-bot.com/v1.0/devices/DEVICE_ID/commands"
sbot_hum_off: "/usr/bin/curl -X POST -H 'Content-Type: application/json' -H 'Authorization: API_TOKEN' -d '{\"command\": \"turnOff\"}' https://api.switch-bot.com/v1.0/devices/DEVICE_ID/commands"
sbot_humidifier: "https://api.switch-bot.com/v1.0/devices/DEVICE_ID/status"
sbot_meter:  "https://api.switch-bot.com/v1.0/devices/DEVICE_ID/status"
```

**Comment by BeardedTinker** [comment]
[Sample switch](https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/switches/switchbot_humidifier.yaml) for SwitchBot Humidifer - it needs to be under `switch:` section in Home Assistant:
```
platform: command_line
switches: 
  switchbot_humidifier:
    command_on: !secret sbot_hum_on
    command_off: !secret sbot_hum_off
    friendly_name: Humidifier
```

[Example of RESTful JSON call](https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/rest/switchbot_humidifier.yaml) for SwitchBot Humidifier - add to `rest:` section in Home Assistant:
```
resource: !secret sbot_humidifier
method: GET
scan_interval: 900
headers:
  Authorization: !secret sbot_api
  Content-Type: 'application/json'
sensor:
  name: Switchbot Humidifier json
  value_template: '{{ value_json.body }}'
  json_attributes_path: "$.body"
  json_attributes:
  - deviceId
  - deviceType
  - nebulizationEfficiency
  - humidity
  - auto
  - childLock
  - sound
  - power
  - temperature
  - lackWater
```

[Example sensors](https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/sensors/switchbot_humidifier.yaml) for SwitchBot Humidifier - add to `sensors:` section in Home Assistant:
```
platform: template
sensors:
  switchbot_humidifier_temp:
    friendly_name: "Humidifier Temperature"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["temperature"] }}'
    unit_of_measurement: "°C"
    device_class: "temperature"
  switchbot_humidifier_humidity:
    friendly_name: "Humidifier humidity"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["humidity"] }}'
    unit_of_measurement: "%"
    device_class: "humidity"
  switchbot_humidifier_nebulization:
    friendly_name: "Humidifier nebulization"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["nebulizationEfficiency"] }}'
    unit_of_measurement: "%"
```

[Example of binary sensors](https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/binary_sensors/switchbot_humidifier.yaml) for SwitchBot Humidifier - add to `binary_sensors:` section in Home Assistant:
```
platform: template
sensors:
  switchbot_humidifier_childlock:
    friendly_name: "Humidifier Child Lock"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["childLock"] }}'
  switchbot_humidifier_sound:
    friendly_name: "Humidifier Sound"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["sound"] }}'
  switchbot_humidifier_power:
    friendly_name: "Humidifier Power"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["power"] }}'
    device_class: "power"
  switchbot_humidifier_water:
    friendly_name: "Humidifier Water"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["lackWater"] }}'
    device_class: "problem"
```

**Comment by BeardedTinker** [comment]
Here is example of code (with links to current version) for SwitchBot Meter.

[Example of RESTful JSON call](https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/rest/switchbot_meter.yaml) for SwitchBot Meter - add to `rest:` section in Home Assistant:
```
resource: !secret sbot_meter
method: GET
scan_interval: 900
headers:
  Authorization: !secret sbot_api
  Content-Type: 'application/json'
sensor:
  name: Switchbot Meter json
  value_template: '{{ value_json.body }}'
  json_attributes_path: "$.body"
  json_attributes:
  - deviceId
  - deviceType    
  - humidity
  - temperature
```

[Example of sensors](https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/sensors/switchbot_humidifier.yaml) for SwitchBot Meter - add in `sensors:` section of Home Assistant:
```
platform: template
sensors:
  switchbot_humidifier_temp:
    friendly_name: "Humidifier Temperature"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["temperature"] }}'
    unit_of_measurement: "°C"
    device_class: "temperature"
  switchbot_humidifier_humidity:
    friendly_name: "Humidifier humidity"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["humidity"] }}'
    unit_of_measurement: "%"
    device_class: "humidity"
  switchbot_humidifier_nebulization:
    friendly_name: "Humidifier nebulization"
    value_template: '{{ states.sensor.switchbot_humidifier_json.attributes["nebulizationEfficiency"] }}'
    unit_of_measurement: "%"
```
