### ISSUE TITLE
Music Assistant

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#96]
Let's look at all of the code necessary to run Music Assistant and connect it to Synology NAS share where media files are.

You need to have SAMBA share that can be from Home Assistant up and running.
I've set it with read-write permission, although, read only should be sufficient.

Music Assistant had previously problems with #recycle folder, so I removed it just in case, although it should work without an issue.

###  Shell Command

Following command is used to create folder in Home Assistant (/media/musicnas) and also connect to it.
Change IP address to match address of your Samba share - don't forget to also change name of folder where media files are (in my case /music), and also username and password to match your setup.

```
shell_command:
  mount_music_folder: "mkdir -p /media/musicnas;mount -t cifs -o vers=3.0,noserverino,username=demo_user,password=demo_password,domain=WORKGROUP //192.168.1.35/music /media/musicnas"

```

### Automation

Each time Home Assistant starts, this automation will trigger and it will create and connect to Samba share by using above shell command.

```
#####
# Automation to trigger Synology NAS Samba mount for Music
#
#####

alias: Mount Synology Music Folder
id: 3b6c7f69-7406-4531-9493-f08e2de71630

description: Mounts Samba share for use with Music Assistant 

trigger:
- platform: homeassistant
  event: start

condition: []

action:
- service: shell_command.mount_music_folder
  data: {}
```

In Home Assistant, after installing Music Assistant and restarting your setup, during configuration, you need to enable this functionality and specify the folder name. In my case it's:
![image](https://user-images.githubusercontent.com/47822612/204601317-803592d3-595a-4cab-b538-9615d014b28c.png)

For other services:
- If you have Spotify (non free version) use username and password to connect to it
- YouTube Music requires email address and cookie of that user
- TuneIn can be used with free service by entering your username
